version: '3'
services:
  api:
    build: ./api
    ports:
      - 3002:3002
    env_file: ./api/.env.docker
  auth:
    build: ./auth
    ports:
      - 3001:3001
    env_file: ./auth/.env.docker
  client:
    build: ./client
    ports:
      - 3000:3000
    env_file: ./client/.env.docker
    depends_on:
      - auth
      - api
